### ISSUE TITLE
error checking for updates

### ISSUE THREAD

**Issue by osu-question** [Hazuki-san/hqOsu-xtreme#10]
![osuissue](https://user-images.githubusercontent.com/77410261/104498214-64912580-55a9-11eb-9249-ec578fa2dd5d.png)

**Comment by DualGradient** [comment]
GitHub issue, try again later

**Comment by gncabar** [comment]
its alery not working same issue :( can u help @Hazuki-san

**Comment by SpookerI** [comment]
@gncabar This is GitHub issue. Create a folder _new

**Comment by gncabar** [comment]
"Create a folder _new" i dont understand

**Comment by SpookerI** [comment]
-_-. Go to your hqosu folder. Create a folder and name it "_new"

**Comment by gncabar** [comment]
![image](https://user-images.githubusercontent.com/77430235/104554252-fe5dde80-564c-11eb-8a64-b9a30fc2c9fc.png)

**Comment by SpookerI** [comment]
🤦 . Don't copy hqosu loader in this folder. Just create it and leave empty

**Comment by gncabar** [comment]
i was delete my yesterday hqosu :( i have just a launcher

**Comment by gncabar** [comment]
but i understand u mean

**Comment by SpookerI** [comment]
well. Then wait

**Comment by gncabar** [comment]
okey thx

**Comment by Hazuki-san** [comment]
Fixed them, have fun.

**Comment by osu-question** [comment]
still not working.

**Comment by DualGradient** [comment]
It does work. Delete everything related to hqOsu and download the latest release. It should work now.
