### ISSUE TITLE
unsupported version

### ISSUE THREAD

**Issue by arimafn** [Hazuki-san/hqOsu-xtreme#3]
![image](https://user-images.githubusercontent.com/75119967/100437472-d8d34080-30b1-11eb-8113-0e2ee8eeb8d2.png)

**Comment by Hazuki-san** [comment]
You need to wait for me until I finish the client patching

**Comment by helpisoutdated** [comment]
yea

**Comment by Gei-user** [comment]
outdate moment

**Comment by Gei-user** [comment]
this is the the osu update go download now

**Comment by Hazuki-san** [comment]
Please wait for #4
