### ISSUE TITLE
Hqosu outdated 

### ISSUE THREAD

**Issue by ImageMaterial89** [Hazuki-san/hqOsu-xtreme#8]
![image](https://user-images.githubusercontent.com/47972401/103172031-339abc00-4859-11eb-97c8-d39304a40f78.png)

Can you update this Hazuki-san?

**Comment by Hazuki-san** [comment]
experimental build

**Comment by Lurinoxi** [comment]
Ah yea i wanted to ask i mean there are some server where the anti cheat sucks but even if the text says u can use the hack i cant ? Any reason
